- name: configure the backend server
  hosts: backend
  become: yes
  tasks:
    - name: diable the existing nodejs tasks/modules/collection
      ansible.builtin.command: dnf module disable nodejs -y


    - name: enable th enodejs:20
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name: install nodejs
      ansible.builtin.dnf: 
        name: nodejs
        state: installed

    - name: adding user
      ansible.builtin.user: 
        name: expense

    - name: create app directory
      ansible.builtin.file:
        path: /app
        state: directory
        mode: '0755'

    #- name: download app code
     # ansible.builtin.command: curl -o /tmp/backend.zip https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
    - name: Unarchive a file that needs to be downloaded (added in 2.0)
      ansible.builtin.unarchive:
        src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
        dest: /app
        remote_src: yes