- name: configure the db server
  hosts: db
  become: yes
  vars:
    login_hosts: db.hkinfo.fyi
  tasks:
    - name: install mysql server
      ansible.builtin.dnf:
        name: mysql server
        status: latest

    - name: ansible start service
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes
#check password already setup or not
    - name: check db connection
      community.mysql.mysql_info:
        login_user: root
        login_password: ExpenseApp@1
        login_host: "{{ login_hosts }}"
        filter: version
      ignore_errors: yes
      register: mysql_connection_output
#print output   
    - name: print output
      ansible.builtin.debug:
        msg: "{{ mysql_connection_output }}"