- name: configure the frontend
  hosts: frontend
  become: yes
  vars:
    login_host: db.hkinfo.fyi
    login_password: ExpenseApp@1
    login_user: root
  tasks:
    - name: install nginx
      ansible.builtin.dnf:
        state: l