- name: configure the frontend server
  hosts: frontend
  become: yes
  vars:
    login_host: db.hkinfo.fyi
    login_password: ExpenseApp@1
    login_user: root
  tasks:
    - name: install nginx
      ansible.builtin.dnf:
        name: nginx
        state: latest

    - name: start and enable nginx
      ansible.builtin.service:
        name: frontend
        state: started
        enabled: yes

    - name: Remove file default html file
      ansible.builtin.file:
        path: /usr/share/nginx/html/*
        state: absent 

   

